version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      voNDZCY8S5h/wymc8NJh03c1CYBzTmAcByiYnPVARzNMxnvk+rTNeW4Zy5cqTXOeMEn1+wArKclhA8aYeVLDFucixp00gWcTi/yjwwzFU1/0MWY+sNQHo/9A4MWvlZaPLtziggsHu2rdhHoi2qij1lV6g6CooB1iQM4HPMGBHSTC+3lJn5RmLFoMN44y+C15WWkx1OlZsf7feHh44M565b9pG9swSs2NVlGJqlXkcM22lIJ4K2lnz3hiV3FqwHPxAJgHt3yB+yodPFJUV5bRWHoujPhzHb6k6cgk+0HXnGNwjGCUHomIuN6eNgH55h2Oj6khbkVojb8f4hJzW5SkcmpsRpIa+ODio7zNdXPCbdRtV4dGnMjxwOMGWnWiVL6hXJMZ6oR/RVRyYxfG9usXVYU3qSFd7BHqEY+gGOC9FY+G1S26E/2psQ48dQgqZ/HVtc6npKHUByVU0UtORtDEfmQRjaZXIGy1IFiyvmn7gbhvZ28akI7vs8leqryzBmxYPfZTYC/15G9h4QnI/DqO5BtJU77xkFFDYcPLdE/w29SuSBhVBUTlRrp7ysF4ZuRnXytSpXksLRgARBAzgGOL9FAf+VW3ZrGSn5mNfpmy+72qqazRTelNkYdSsJKCWSv4vB/acxl7lNkjbY1YU+QvN7x5+pc5no6IcwmjIvgpGCI=
